### ISSUE TITLE
Retrieve outstanding balance to be claimed

### ISSUE THREAD

**Issue by VVander** [nodeset-org/hyperdrive-stakewise#2]
Users should know their individual reward balances which have before they claim anything. This is relatively easy to do by simply calling `getETHBalance(address` on `SplitMain`. There is one `SplitMain` deployment per network, [see the docs for more info](https://docs.splits.org/core/split).

The outstanding amount to claim should be displayed in the following commands:
- [ ] `hyperdrive stakewise status`
- [ ] `hyperdrive stakewise wallet claim-rewards`

**Comment by jclapis** [comment]
This is in now, but for reference Stakewise doesn't send you ETH; it sends you an ERC20 (the token represented by their Vault contract) so you need to use `getERC20Balance()`.
