### ISSUE TITLE
Systemd service error

### ISSUE THREAD

**Issue by aliask** [nodeset-org/hyperdrive-stakewise#29]
Hi there.

When installing the systemd service via the install command, I get the following error:
```
Failed to start nodeset.service: Unit nodeset.service has a bad unit file setting.
...
Dec 18 11:15:42 staker-nodeset systemd[1]: nodeset.service: Service has more than one ExecStart= setting, which is only allowed for Type=oneshot services. Refusing.
```

I updated my `nodeset.service` file as follows to resolve the issue.
```diff
diff --git a/local/nodeset.service b/local/nodeset.service
index f966aa3..d944dcc 100644
--- a/local/nodeset.service
+++ b/local/nodeset.service
@@ -4,10 +4,11 @@ After=network.target

 [Service]
 ExecStart=nodeset start
-ExecStart=nodeset shutdown
-Type=exec
+ExecStop=nodeset shutdown
+Type=simple
+RemainAfterExit=yes
 Restart=no

 [Install]
 WantedBy=default.target
-RequiredBy=network.target
\ No newline at end of file
+RequiredBy=network.target
```

**Comment by VVander** [comment]
Thank you for the report @aliask! Hopefully this commit fixes this issue: 01ffb7772313c566166109a91d18ef0568272639

We haven't yet started testing outside of a dev environment (which doesn't have systemd), so you'll have to let me know if this fixes it.

**Comment by aliask** [comment]
Hey Wander. When I initially tried just this change the service would start, and then stop immediately afterwards. Changing the service type and other setting was necessary for it to work "normally" for me.

**Comment by VVander** [comment]
@aliask thanks for the update. Can you try this PR and let me know if it fixes it for you? 

https://github.com/nodeset-org/hyperdrive-stakewise/pull/33

**Comment by aliask** [comment]
@VVander - looks fine, although using `oneshot` instead of `simple` makes this service blocking - no other services can start until nodeset completes booting.

https://trstringer.com/simple-vs-oneshot-systemd-service/

Not sure if that is intended, but the PR will fix the errors and it'll work.

**Comment by VVander** [comment]
@aliask the intention was to allow users create their own services which depend on this one, but I suppose that's what the `After=` field is for. I'll update the PR to use `simple` and merge it. Thank you for your help in testing this!
