### ISSUE TITLE
Fetch deposit data file from API

### ISSUE THREAD

**Issue by VVander** [nodeset-org/hyperdrive-stakewise#31]
Create a ~10min cron job to check for an updated deposit data file and download it:

- check timestamp metadata endpoint to determine if local file is out of date
- fetch from file endpoint if so

Exact urls tbd

When the new deposit data file is fetched, the stakewise v3-operator container needs to be restarted to reload it

**Comment by jclapis** [comment]
Closed as of https://github.com/nodeset-org/hyperdrive/commit/2ce45fe666e49e2cb0625c81ad6279869a84d143.
