### ISSUE TITLE
All commands (except `status`) should first check if the wallet is initialized

### ISSUE THREAD

**Issue by VVander** [nodeset-org/hyperdrive-stakewise#7]
Currently, you can generate keys and upload them to NS (which means they may be added to the vault's deposit file) even if your stakewise wallet is not initialized and therefore no deposit transaction can be completed.

To prevent this, we should ensure the stakewise wallet is initialized before doing anything with the SW module.

**Comment by jclapis** [comment]
Added in 0d89931 and ec48daa.
